pre-processing [github "innovation graph" data on repository topics](https://github.com/github/innovationgraph) for [this notebook on correlation and clustering](correlation-and-clustering-with-pandas.ipynb).

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.rcParams["figure.figsize"] = (10, 4)

grab the data from the github repo

In [2]:
!curl -L -O https://raw.githubusercontent.com/github/innovationgraph/main/data/topics.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1628k  100 1628k    0     0  4687k      0 --:--:-- --:--:-- --:--:-- 4692k

load into a data frame, poke around a bit

In [25]:
df = pd.read_csv("topics.csv")

In [26]:
df_by_topic = df.groupby(["iso2_code", "topic"], as_index=False).sum()[["iso2_code", "topic", "num_pushers"]]

In [27]:
df_by_topic[df_by_topic["iso2_code"] == "US"]

     iso2_code           topic  num_pushers
4374        US              3d         6084
4375        US     3d-graphics         2046
4376        US     3d-printing         2049
4377        US            a11y         2287
4378        US     accelerator          219
...        ...             ...          ...
5553        US  zero-knowledge          432
5554        US      zero-trust          103
5555        US             zig         1030
5556        US             zsh        10658
5557        US           zshrc          642

[1184 rows x 3 columns]

In [28]:
df[(df["iso2_code"] == "US") & (df["topic"] == "youtube")]["num_pushers"].sum()

np.int64(5594)

group the numbers by iso2 country code, summing the columns and getting just the number of pushers, just to validate my intuitions about how the data works

In [30]:
df_pushers_by_iso2_code = df.groupby("iso2_code").sum()[["num_pushers"]]

In [31]:
df_pushers_by_iso2_code.loc["AE"]

num_pushers    27317
Name: AE, dtype: int64

add a field to the "by topic" data frame with the percentage of total pushes in a given iso2 code with the given topic

In [34]:
df_by_topic["percent"] = df_by_topic.apply(
    lambda x: x["num_pushers"] / df_pushers_by_iso2_code.loc[x["iso2_code"]],
    axis=1
)

here are the percentage values for the US, sorted in reverse order:

In [35]:
df_by_topic[df_by_topic["iso2_code"] == "US"].sort_values("percent", ascending=False).head(25)

     iso2_code             topic  num_pushers   percent
4576        US            config       554233  0.076421
4820        US     github-config       549672  0.075792
5219        US            python       203861  0.028109
4923        US        javascript       127758  0.017616
5244        US             react       113795  0.015691
4851        US     hacktoberfest       112043  0.015449
5461        US        typescript        84339  0.011629
4995        US  machine-learning        75627  0.010428
4920        US              java        72550  0.010004
5103        US            nodejs        65101  0.008976
4686        US            docker        56712  0.007820
4825        US            golang        51090  0.007045
4608        US               css        46078  0.006353
4950        US        kubernetes        45999  0.006343
5298        US              rust        44672  0.006160
4881        US              html        44589  0.006148
4647        US     deep-learning        43680  0.006023
4823        US                go        43078  0.005940
5222        US           python3        39813  0.005490
4420        US               api        39217  0.005407
4460        US               aws        35382  0.004879
4974        US             linux        35128  0.004844
5251        US           reactjs        34110  0.004703
4694        US          dotfiles        33508  0.004620
5527        US           website        33294  0.004591

overall percentages for each topic

In [36]:
df_by_topic.groupby("topic").sum(numeric_only=True).sort_values("percent", ascending=False).head(40)

                  num_pushers    percent
topic
config                4702742  51.959890
github-config         4676027  51.713467
python                1110151   3.497584
javascript             882833   2.831236
react                  746979   2.499952
typescript             604812   1.848471
hacktoberfest          598945   1.633866
java                   496241   1.224210
nodejs                 434572   0.843470
docker                 352998   0.657566
css                    345023   0.614425
html                   327329   0.551129
reactjs                289744   0.472683
golang                 241207   0.383670
machine-learning       283688   0.371935
php                    222609   0.369647
nextjs                 199938   0.341215
api                    238545   0.325428
tailwindcss            159215   0.285919
rust                   197790   0.266977
android                198431   0.263113
linux                  185512   0.244977
go                     176275   0.237734
kubernetes             178906   0.228648
python3                207591   0.213294
vue                    117069   0.193754
blog                   124024   0.193261
deep-learning          154655   0.186193
cpp                    157967   0.168635
mongodb                143709   0.162029
dotfiles               136331   0.159225
website                151057   0.158425
documentation          129916   0.152612
ai                     111561   0.148736
cli                    139872   0.140921
html5                  110340   0.127366
game                   131000   0.122820
mysql                  105176   0.116902
postgresql             111642   0.111617
blockchain              86370   0.111506

top forty topics by percent, though I've skipped the first two entries (`config` and `github-config`) because of their unusual commonality

In [37]:
top40 = df_by_topic.groupby("topic").sum(numeric_only=True).sort_values("percent", ascending=False).head(42).tail(40).index.values

In [38]:
top40

<StringArray>
[          'python',       'javascript',            'react',
       'typescript',    'hacktoberfest',             'java',
           'nodejs',           'docker',              'css',
             'html',          'reactjs',           'golang',
 'machine-learning',              'php',           'nextjs',
              'api',      'tailwindcss',             'rust',
          'android',            'linux',               'go',
       'kubernetes',          'python3',              'vue',
             'blog',    'deep-learning',              'cpp',
          'mongodb',         'dotfiles',          'website',
    'documentation',               'ai',              'cli',
            'html5',             'game',            'mysql',
       'postgresql',       'blockchain',           'csharp',
         'database']
Length: 40, dtype: str

pivot the topic table, so that we have one column per topic, and one rwo per iso2 code, but only use the top forty topics overall

In [19]:
df_iso2_top40_topics = df_by_topic.pivot(index="iso2_code", columns="topic", values="percent")[top40]

some of these values will be undefined, which means that they are effectively zero percent, so fill in with 0.0:

In [39]:
df_iso2_top40_topics.fillna(0.0, inplace=True)

topic,python,javascript,react,typescript,hacktoberfest,java,nodejs,docker,css,html,...,documentation,ai,cli,html5,game,mysql,postgresql,blockchain,csharp,database
iso2_code,,,,,,,,,,,,,,,,,,,,,
AE,0.024893,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
AR,0.047572,0.066972,0.058110,0.034834,0.003890,0.026181,0.033612,0.010398,0.036454,0.030399,...,0.000000,0.000000,0.000000,0.012277,0.000000,0.006418,0.001453,0.002256,0.000000,0.0000
AT,0.138945,0.080491,0.030061,0.063392,0.107329,0.075530,0.000000,0.033102,0.000000,0.000000,...,0.025032,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
AU,0.064822,0.045350,0.048456,0.042244,0.040950,0.022481,0.026591,0.023581,0.015622,0.016417,...,0.011090,0.004690,0.011192,0.000000,0.009665,0.000000,0.000000,0.002246,0.003305,0.0000
BD,0.022675,0.042556,0.035059,0.017608,0.000960,0.011314,0.027498,0.001770,0.024923,0.022981,...,0.000000,0.001189,0.000000,0.017907,0.000000,0.003870,0.003325,0.000000,0.000000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
US,0.028109,0.017616,0.015691,0.011629,0.015449,0.010004,0.008976,0.007820,0.006353,0.006148,...,0.004220,0.004401,0.004478,0.001766,0.004008,0.002359,0.002978,0.002882,0.003349,0.0041
UZ,0.000000,0.007089,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
VE,0.000000,0.020529,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
VN,0.023450,0.025192,0.026674,0.024785,0.003132,0.018866,0.023435,0.012219,0.008124,0.007065,...,0.000000,0.002649,0.000000,0.000000,0.000000,0.005567,0.003571,0.000000,0.001059,0.0000
ZA,0.024255,0.029943,0.013539,0.003104,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000

In [42]:
df_iso2_top40_topics = df_iso2_top40_topics[df_iso2_top40_topics.sum(axis=1) > 0]

test: which topics are most correlated with the "api" topic?

In [44]:
df_iso2_top40_topics.corr()["api"].sort_values(ascending=False).head(10)

topic
api                 1.000000
linux               0.789461
php                 0.738937
cli                 0.677325
website             0.664250
python3             0.651073
game                0.649213
docker              0.632730
rust                0.631813
machine-learning    0.597251
Name: api, dtype: float64

how about rust?

In [48]:
df_iso2_top40_topics.corr()["rust"].sort_values(ascending=False).head(10)

topic
rust                1.000000
go                  0.880176
linux               0.860596
dotfiles            0.831995
cli                 0.812899
machine-learning    0.730714
golang              0.720829
docker              0.696625
deep-learning       0.660745
blockchain          0.644627
Name: rust, dtype: float64

the transpose of this data frame will have a column for every country and a row for every topic. which country is most like Denmark?

In [49]:
df_iso2_top40_topics.T.corr()["DK"].sort_values(ascending=False).head(10)

iso2_code
DK    1.000000
NZ    0.962684
BE    0.918585
AT    0.884261
IE    0.868756
CZ    0.845954
GB    0.841698
EU    0.840139
US    0.837753
HU    0.836701
Name: DK, dtype: float64

or like canada?

In [52]:
df_iso2_top40_topics.T.corr()["CA"].sort_values(ascending=False).head(10)

iso2_code
CA    1.000000
GB    0.962496
ES    0.962358
FI    0.959812
AU    0.958165
US    0.957041
PL    0.955953
PT    0.954114
EU    0.938270
RO    0.919154
Name: CA, dtype: float64

looks good, let's export

In [53]:
with open("github-topics-by-economy.csv", "w") as fh:
    fh.write(df_iso2_top40_topics.to_csv())